version: "3.6"

services:

  # Backend API
  face_recognition_api: 
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/face_recognition_api
    environment:
      POSTGRES_URI: postgres://sally:secret@postgres:5432/face_recognition_docker
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/face_recognition_api

  # Postgres
  postgres:
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: face_recognition_docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"