BEGIN TRANSACTION;

CREATE TABLE users
(
  id serial PRIMARY KEY,
  name VARCHAR(100),
  age SMALLINT,
  country VARCHAR(20),
  email text UNIQUE NOT NULL,
  entries BIGINT DEFAULT 0,
  joined TIMESTAMP NOT NULL
);

COMMIT;